services:

  backend_app:
    container_name: backend_app
    build: .
    volumes:
      - ./backend_app:/var/www/html
    ports:
      - 5000:80
  
  mysql_server:
    container_name: mysql_server
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innoscripta_test
    ports:
    - 3306:3306
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080